import telebot
import os
import time
import json
import zipfile
from groq import Groq
from flask import Flask
from threading import Thread

# --- [ CONFIG ] ---
KEY_POOL = [
    "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",
    "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",
    "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",
    "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"
]
current_key_index = 0

BOT_TOKEN = "8693996706:AAFhDMaiIPwps8woQvHSuQUpALSn5VsAR9Q"
bot = telebot.TeleBot(BOT_TOKEN)
app = Flask('')

chat_memories = {}

# --- [ CORE LOGIC ] ---
def get_groq_response(user_id, user_input):
    global current_key_index
    if user_id not in chat_memories:
        chat_memories[user_id] = [{"role": "system", "content": "You are Pardhan AI by @beast_harry. Expert in Python and C."}]
    
    chat_memories[user_id].append({"role": "user", "content": user_input})
    
    for _ in range(len(KEY_POOL)):
        try:
            client = Groq(api_key=KEY_POOL[current_key_index])
            completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=chat_memories[user_id],
                temperature=0.6,
                max_tokens=4096
            )
            ans = completion.choices[0].message.content
            chat_memories[user_id].append({"role": "assistant", "content": ans})
            return ans
        except Exception as e:
            if "429" in str(e):
                current_key_index = (current_key_index + 1) % len(KEY_POOL)
                continue
            else: return f"❌ Error: {str(e)}"
    return "❌ All Keys Exhausted."

# --- [ ZIP HANDLER ] ---
def create_zip_and_send(chat_id, content, filename="beast_code.py"):
    zip_name = "Pardhan_Project.zip"
    
    # 1. Temporary file likho
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    
    # 2. Zip file banao
    with zipfile.ZipFile(zip_name, 'w') as zipf:
        zipf.write(filename)
    
    # 3. Send document
    with open(zip_name, 'rb') as f:
        bot.send_document(chat_id, f, caption="📂 **Project Zip File**\nGenerated by @beast\_harry", parse_mode="Markdown")
    
    # 4. Cleanup
    os.remove(filename)
    os.remove(zip_name)

# --- [ BOT HANDLERS ] ---
@bot.message_handler(commands=['zip'])
def handle_zip_request(message):
    prompt = message.text.replace("/zip", "").strip()
    if not prompt:
        bot.reply_to(message, "⚠️ Please provide a prompt. Example: `/zip write a python snake game`", parse_mode="Markdown")
        return
    
    status = bot.reply_to(message, "📂 **Preparing Zip Archive...**", parse_mode="Markdown")
    response = get_groq_response(message.from_user.id, prompt)
    
    # Zip bhejo
    create_zip_and_send(message.chat.id, response)
    
    # Chat message update
    bot.edit_message_text("✅ **Zip File Sent Successfully!**", message.chat.id, status.message_id, parse_mode="Markdown")

@bot.message_handler(func=lambda m: True)
def handle_chat(message):
    bot.send_chat_action(message.chat.id, 'typing')
    status_msg = bot.reply_to(message, "⚡ **Thinking...**", parse_mode="Markdown")
    response = get_groq_response(message.from_user.id, message.text)
    
    final_design = f"🤖 **PARDHAN INTELLIGENCE**\n━━━━━━━━━━━━━━━━━━━━\n\n{response}\n\n━━━━━━━━━━━━━━━━━━━━\n⚡ *By @beast\_harry*"
    
    try:
        if len(final_design) > 4000:
            bot.edit_message_text("⚠️ Message too long, use `/zip` command for large projects.", message.chat.id, status_msg.message_id)
        else:
            bot.edit_message_text(final_design, message.chat.id, status_msg.message_id, parse_mode="Markdown")
    except:
        bot.edit_message_text(final_design, message.chat.id, status_msg.message_id)

@app.route('/')
def home(): return "SYSTEM_STABLE"

if __name__ == "__main__":
    Thread(target=lambda: app.run(host='0.0.0.0', port=int(os.environ.get("PORT", 8080)))).start()
    bot.infinity_polling()
